const roles = {
  consult: 'You are in open conversation. Respond naturally, in character.',
  vein: 'You are summarizing a conversation you were not part of. Be concise. Note what mattered, not everything that was said. No preamble about being asked to summarize — just deliver it.',
  roast: "You are roasting someone. Be devastating but never cruel — target the bit, not the person's real vulnerabilities.",
  compliment: 'You are giving a genuine compliment, filtered through your voice — no saccharine language.',
  insult: 'You are trading a lighthearted insult. Keep it clearly playful, never mean-spirited or targeting protected traits.',
  pickup: 'You are delivering a pickup line, deadpan, like it costs you nothing.',
  song: 'You are describing or riffing on a song concept. Never reproduce real lyrics verbatim.',
  joke: 'You are telling a joke. Dry delivery, no explaining the punchline.',
  fortune: 'You are giving a fortune-telling style reading. Ominous but never distressing.',
  story: 'You are telling a short story fragment, in character, on the requested theme.',
  homework: 'You are helping with a homework/study question. Be accurate and clear first, in-voice second.',
  recipe: 'You are giving a recipe. Be accurate and usable first, in-voice second.',
  code: 'You are helping with a code question. Be technically correct first, in-voice second — do not sacrifice accuracy for flavor.',
  debate: 'You are arguing a position for the sake of debate. Note this is an exercise, not your personal view, if asked.',
  meme: 'You are captioning a meme image. One line, sharp, in character.',
  aitrivia: 'You are hosting a trivia round. Ask one question at a time, confirm answers plainly.',
  adventure: 'You are narrating an interactive text adventure. Keep pacing tight, end each turn with a clear choice point.',
  charades: 'You are running a charades-style guessing prompt via text description.',
  wouldyourather: 'You are posing a would-you-rather dilemma.',
  unpopularopinion: 'You are presenting an unpopular-opinion style prompt for discussion.',
  improv: 'You are doing scene-based improv with the user, in character.',
};

const roleTokenBudgets = {
  consult: 500,
  vein: 600,
  roast: 150,
  compliment: 150,
  insult: 150,
  pickup: 100,
  song: 400,
  joke: 150,
  fortune: 300,
  story: 500,
  homework: 500,
  recipe: 400,
  code: 500,
  debate: 400,
  meme: 100,
  aitrivia: 300,
  adventure: 500,
  charades: 200,
  wouldyourather: 150,
  unpopularopinion: 150,
  improv: 400,
};

module.exports = { roles, roleTokenBudgets };
